name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for commit message validation

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --group dev

      # Validate commit messages for PRs
      - name: Validate commit messages
        if: github.event_name == 'pull_request'
        run: |
          uv run cz check --rev-range origin/main..HEAD

      - name: Lint
        run: uv run ruff check --config ./pyproject.toml .

      - name: Test
        run: uv run pytest

      - name: Build
        run: uv build
